name: SDK Publish

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
jobs:
  publish-secondary:
    runs-on: macos-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Update bundler
      run: gem install bundler
        
    - name: Install bundler dependencies
      run: bundle install

    - name: Deploy to Cocoapods Secondary
      run: |
          pod lib lint iOSSDKReleaseSecondary.podspec --allow-warnings
          pod trunk push iOSSDKReleaseSecondary.podspec --allow-warnings
      env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
    
  delay:
    needs: [publish-secondary]
    runs-on: ubuntu-latest
    steps:
    
    - name: Delay for 15 minutes
      run: sleep 900
      
  check-with-retry:
    needs: [delay]
    runs-on: macos-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Update bundler
      run: gem install bundler
        
    - name: Install bundler dependencies
      run: bundle install
    
    - uses: nick-fields/retry@v3
      with:
        timeout_minutes: 5
        max_attempts: 12
        command: |
            pod repo update
            pod lib lint --allow-warnings
        retry_on: error
        retry_wait_seconds: 300
  
  publish:
    needs: [check-with-retry]
    runs-on: macos-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Update bundler
      run: gem install bundler
        
    - name: Install bundler dependencies
      run: bundle install

    - name: Deploy to Cocoapods Main
      run: |
          pod repo update
          pod lib lint --allow-warnings
          pod trunk push iOSSDKReleaseMain.podspec --allow-warnings
      env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
