name: SDK Publish

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
jobs:
  publish-secondary:
    runs-on: macos-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Update bundler
      run: gem install bundler
        
    - name: Install bundler dependencies
      run: bundle install

    - name: Deploy to Cocoapods Secondary
      run: |
          pod lib lint iOSSDKReleaseSecondary.podspec --allow-warnings
          pod trunk push iOSSDKReleaseSecondary.podspec --allow-warnings
      env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
          
  check-with-retry:
    needs: [publish-secondary]
    runs-on: macos-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Update bundler
      run: gem install bundler
        
    - name: Install bundler dependencies
      run: bundle install
    
    - uses: nick-fields/retry@v3
      with:
        timeout_minutes: 15
        max_attempts: 20
        command: |
            pod repo update
            pod lib lint --allow-warnings
        on_retry_command: pod repo update
        retry_on: error
        retry_wait_seconds: 120
    
#  delay:
#    needs: [publish-secondary]
#    runs-on: ubuntu-latest
#    steps:
#    
#    - name: Delay for 20 minutes
#      run: sleep 1200
  
  publish:
    needs: [check-with-retry]
    runs-on: macos-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Update bundler
      run: gem install bundler
        
    - name: Install bundler dependencies
      run: bundle install

    - name: Deploy to Cocoapods Main
      run: |
          pod repo update
          pod lib lint --allow-warnings
          pod trunk push iOSSDKReleaseMain.podspec --allow-warnings
      env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
